<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="1_RecordTypes/**/*.cs" />
    <Compile Remove="2_StringVeText/**/*.cs" />
    <Compile Remove="3_NumericTypes/**/*.cs" />
    <Compile Remove="4_SartlarVeDonguler/**/*.cs" />
    <Compile Remove="5_ListCollections/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="1_RecordTypes/RecordTypes.csproj" />
    <ProjectReference Include="2_StringVeText/StringVeText.csproj" />
    <ProjectReference Include="3_NumericTypes/NumericTypes.csproj" />
    <ProjectReference Include="4_SartlarVeDonguler/SartlarVeDonguler.csproj" />
    <ProjectReference Include="5_ListCollections/ListCollections.csproj" />
  </ItemGroup>
</Project>
